### ISSUE TITLE
test/e2e.sh should look at env var for WEBUI_START_XVFB

### ISSUE THREAD

**Issue by crobby** [radanalyticsio/oshinko-webui#112]
As of now, the test script always runs the test-e2e script with WEBUI_START_XVFB=false.  Ideally, it could pick up an optional env var (that might be set by a test environment (Jenkins or Travis-ci maybe) that would let the script set up the Xvfb magic (or maybe even specify the command to be run to set it up since it seems to vary between distros).

**Comment by crobby** [comment]
I'm thinking that maybe this isn't really necessary.  We already have this working locally, in Travis-ci, and in Jenkins.  Why muddy the water?

**Comment by tmckayus** [comment]
@crobby is this still an issue do you think?

**Comment by crobby** [comment]
No really necessary.  I'll close this.
