### ISSUE TITLE
Binary now available for use instead of building binary in containers

### ISSUE THREAD

**Issue by zmhassan** [radanalyticsio/oshinko-webui#55]
https://github.com/radanalyticsio/oshinko-webui/blob/master/Dockerfile#L14-L18

Can be replaced with

` wget https://github.com/radanalyticsio/oshinko-cli/releases/download/v0.2.1/oshinko-cli_v0.2.1_linux_amd64.tar.gz && tar -zxvf oshinko-cli_v0.2.1_linux_amd64.tar.gz `

**Comment by crobby** [comment]
Now grabbing from the releases.  Thanks.
